apiVersion: v1
kind: Service
metadata:
  name: userapi-service
spec:
  type: LoadBalancer
  ports:
    - name: userapi-api
      port: 3000
      targetPort: 8000
    - name: userapi-redis
      port: 6379
      targetPort: 6379
  selector:
    app: userapi