# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Do not re-install vbguest plugins
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vm.provider :virtualbox do |vb|
      config.vbguest.auto_update = false
    end
  end

  # VM configuration
  config.vm.define "userapi_server" do |server|
    config.vm.box = "markush81/centos7-vbox-guestadditions"
    config.vm.box_check_update = true
    config.vm.network "forwarded_port", guest: 80, host: 3000, host_ip: "127.0.0.1"
    config.vm.synced_folder "../userapi", "/userapi"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "userapi.server.local"
        vb.memory = "2048"
        vb.cpus = "1"
    end
  end

  # VM provisioning
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbooks/run.yml"
    ansible.tags = ["install", "check"]
  end
end
